//! Emit `tinker-http.js` (JSDoc + `fetch` helpers).

use crate::http::{ErrorCode, HTTP_ROUTES, LanguageId, Listener};

/// JavaScript module text for `generated/tinker-http.js`.
#[must_use]
pub fn javascript_module() -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(TYPEDEFS);
    out.push_str(&error_codes_js());
    out.push_str(&language_ids_js());
    out.push_str(&routes_js());
    out.push_str(HELPERS);
    out
}

fn error_codes_js() -> String {
    let mut s = String::from("export const errorCodes = [\n");
    for code in [
        ErrorCode::Full,
        ErrorCode::UnavailableLanguage,
        ErrorCode::LanguageMismatch,
        ErrorCode::UnknownProblem,
        ErrorCode::BadToken,
        ErrorCode::Denied,
        ErrorCode::Expired,
        ErrorCode::StartFailed,
        ErrorCode::BadRequest,
    ] {
        s.push_str("  '");
        s.push_str(code.as_str());
        s.push_str("',\n");
    }
    s.push_str("];\n\n");
    s
}

fn language_ids_js() -> String {
    let mut s = String::from("export const languageIds = [\n");
    for id in LanguageId::all() {
        s.push_str("  '");
        s.push_str(id.as_str());
        s.push_str("',\n");
    }
    s.push_str("];\n\n");
    s
}

fn routes_js() -> String {
    let mut s = String::from("export const httpRoutes = [\n");
    for r in HTTP_ROUTES {
        let listener = match r.listener {
            Listener::Public => "public",
            Listener::Admin => "admin",
        };
        s.push_str("  { name: '");
        s.push_str(r.name);
        s.push_str("', listener: '");
        s.push_str(listener);
        s.push_str("', method: '");
        s.push_str(r.method);
        s.push_str("', path: '");
        s.push_str(r.path);
        s.push_str("' },\n");
    }
    s.push_str("];\n\n");
    s
}

const HEADER: &str = "\
/**
 * HTTP JSON helpers for the Tinker public and admin listeners.
 * Generated by `tinker codegen`. Do not edit.
 */

";

const TYPEDEFS: &str = "\
/**
 * @typedef {object} ApplyBody
 * @property {string} display_name
 */

/**
 * @typedef {object} ApplyResponse
 * @property {string} request_id
 * @property {string} wait_token
 * @property {number} expires_at
 */

/**
 * @typedef {object} ApproveBody
 * @property {number|null} [ttl_seconds]
 */

/**
 * @typedef {object} LoginBody
 * @property {string} password
 */

/**
 * @typedef {object} EnabledBody
 * @property {boolean} enabled
 */

/**
 * @typedef {object} ExtendBody
 * @property {number} ttl_seconds
 */

/**
 * @typedef {object} ErrorBody
 * @property {string} error
 * @property {string} message
 */

";

const HELPERS: &str = r#"
/**
 * Join `baseUrl` and `path` with a linear scan of trailing slashes.
 * @param {string} baseUrl
 * @param {string} path
 * @returns {string}
 */
export function joinUrl(baseUrl, path) {
  const base = String(baseUrl);
  let end = base.length;
  while (end > 0 && base.charCodeAt(end - 1) === 47) {
    end -= 1;
  }
  if (path.charCodeAt(0) === 47) {
    return base.slice(0, end) + path;
  }
  return base.slice(0, end) + '/' + path;
}

/**
 * @param {string} baseUrl
 * @param {string} path
 * @param {string} method
 * @param {unknown} [body]
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
function send(baseUrl, path, method, body, init) {
  const headers = Object.assign(
    { accept: 'application/json' },
    body !== undefined ? { 'content-type': 'application/json' } : {},
    init && init.headers,
  );
  const opts = Object.assign({}, init, { method: method, headers: headers });
  if (body !== undefined) {
    opts.body = JSON.stringify(body);
  }
  return fetch(joinUrl(baseUrl, path), opts);
}

/**
 * POST /v1/access-requests
 * @param {string} baseUrl
 * @param {ApplyBody} body
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function apply(baseUrl, body, init) {
  return send(baseUrl, '/v1/access-requests', 'POST', body, init);
}

/**
 * GET /v1/access-requests/{request_id}
 * @param {string} baseUrl
 * @param {string} requestId
 * @param {string} waitToken
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function getAccessRequest(baseUrl, requestId, waitToken, init) {
  const headers = Object.assign(
    { authorization: 'Bearer ' + waitToken },
    init && init.headers,
  );
  return send(
    baseUrl,
    '/v1/access-requests/' + encodeURIComponent(requestId),
    'GET',
    undefined,
    Object.assign({}, init, { headers: headers }),
  );
}

/**
 * GET /v1/languages
 * @param {string} baseUrl
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function languages(baseUrl, init) {
  return send(baseUrl, '/v1/languages', 'GET', undefined, init);
}

/**
 * GET /v1/problems
 * @param {string} baseUrl
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function problems(baseUrl, init) {
  return send(baseUrl, '/v1/problems', 'GET', undefined, init);
}

/**
 * POST /v1/login
 * @param {string} baseUrl
 * @param {LoginBody} body
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function login(baseUrl, body, init) {
  const opts = Object.assign({ credentials: 'include' }, init);
  return send(baseUrl, '/v1/login', 'POST', body, opts);
}

/**
 * POST /v1/logout
 * @param {string} baseUrl
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function logout(baseUrl, init) {
  const opts = Object.assign({ credentials: 'include' }, init);
  return send(baseUrl, '/v1/logout', 'POST', undefined, opts);
}

/**
 * GET /v1/access-requests (admin)
 * @param {string} baseUrl
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function listAccessRequests(baseUrl, init) {
  const opts = Object.assign({ credentials: 'include' }, init);
  return send(baseUrl, '/v1/access-requests', 'GET', undefined, opts);
}

/**
 * POST /v1/access-requests/{request_id}/approve
 * @param {string} baseUrl
 * @param {string} requestId
 * @param {ApproveBody} body
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function approve(baseUrl, requestId, body, init) {
  const opts = Object.assign({ credentials: 'include' }, init);
  return send(
    baseUrl,
    '/v1/access-requests/' + encodeURIComponent(requestId) + '/approve',
    'POST',
    body,
    opts,
  );
}

/**
 * POST /v1/access-requests/{request_id}/deny
 * @param {string} baseUrl
 * @param {string} requestId
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function deny(baseUrl, requestId, init) {
  const opts = Object.assign({ credentials: 'include' }, init);
  return send(
    baseUrl,
    '/v1/access-requests/' + encodeURIComponent(requestId) + '/deny',
    'POST',
    undefined,
    opts,
  );
}

/**
 * GET /v1/sessions
 * @param {string} baseUrl
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function listSessions(baseUrl, init) {
  const opts = Object.assign({ credentials: 'include' }, init);
  return send(baseUrl, '/v1/sessions', 'GET', undefined, opts);
}

/**
 * POST /v1/sessions/{session_id}/revoke
 * @param {string} baseUrl
 * @param {string} sessionId
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function revoke(baseUrl, sessionId, init) {
  const opts = Object.assign({ credentials: 'include' }, init);
  return send(
    baseUrl,
    '/v1/sessions/' + encodeURIComponent(sessionId) + '/revoke',
    'POST',
    undefined,
    opts,
  );
}

/**
 * POST /v1/sessions/{session_id}/extend
 * @param {string} baseUrl
 * @param {string} sessionId
 * @param {ExtendBody} body
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function extend(baseUrl, sessionId, body, init) {
  const opts = Object.assign({ credentials: 'include' }, init);
  return send(
    baseUrl,
    '/v1/sessions/' + encodeURIComponent(sessionId) + '/extend',
    'POST',
    body,
    opts,
  );
}

/**
 * POST /v1/languages/{id}/enabled
 * @param {string} baseUrl
 * @param {string} languageId
 * @param {EnabledBody} body
 * @param {RequestInit} [init]
 * @returns {Promise<Response>}
 */
export function setLanguageEnabled(baseUrl, languageId, body, init) {
  const opts = Object.assign({ credentials: 'include' }, init);
  return send(
    baseUrl,
    '/v1/languages/' + encodeURIComponent(languageId) + '/enabled',
    'POST',
    body,
    opts,
  );
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn module_lists_stop_exports() {
        let js = javascript_module();
        for name in ["apply", "approve", "languages", "problems", "login"] {
            assert!(js.contains(&format!("export function {name}(")), "{name}");
            assert!(js.contains(&format!("name: '{name}'")), "route {name}");
        }
        assert!(js.contains("Generated by `tinker codegen`"));
        assert!(js.contains("export const httpRoutes"));
        assert!(js.contains("export const errorCodes"));
        assert!(js.contains("export const languageIds"));
        assert!(js.contains("'python'"));
        assert!(js.contains("'full'"));
        assert!(js.contains("listener: 'public'"));
        assert!(js.contains("listener: 'admin'"));
        assert!(js.contains("joinUrl"));
        assert!(!js.contains("eval("));
    }
}
