[package]
name = "tinker-protocol"
description = "HTTP JSON types and tinker-http.js codegen input"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true
